import { Emitter } from '../utils/events.js';
import { TrackerClient } from './TrackerClient.js';
import { roomInfoHash, trackerPeerId } from '../utils/ids.js';
/** Implements the WebTorrent WebSocket announce offer/answer handshake only. */
export class SignalingManager extends Emitter {
  constructor({ trackers, peerId, offerFactory, answerFactory, answerHandler, announceInterval = 25000 }) { super(); this.trackers = trackers.map((url) => new TrackerClient(url)); this.peerId = trackerPeerId(peerId); this.offerFactory = offerFactory; this.answerFactory = answerFactory; this.answerHandler = answerHandler; this.announceInterval = announceInterval; this.room = null; this.infoHash = null; this.timer = null; this.pending = new Map(); }
  async join(room) { this.leave(); this.room = room; this.infoHash = await roomInfoHash(room); for (const tracker of this.trackers) { tracker.on('open', () => this.announce(tracker)); tracker.on('message', (message) => this.#message(tracker, message)); tracker.on('error', (error) => this.emit('error', error)); tracker.connect(); } this.timer = setInterval(() => this.announce(), this.announceInterval); }
  leave() { clearInterval(this.timer); this.timer = null; if (this.infoHash) for (const tracker of this.trackers) tracker.send(this.#base({ event: 'stopped', numwant: 0 })); this.pending.clear(); this.room = this.infoHash = null; }
  close() { this.leave(); for (const tracker of this.trackers) tracker.close(); }
  async announce(one) { if (!this.infoHash) return; const targets = one ? [one] : this.trackers; await Promise.all(targets.map(async (tracker) => { if (!tracker.socket || tracker.socket.readyState !== WebSocket.OPEN) return; try { const offerId = tracker.newOfferId(); const offer = await this.offerFactory(offerId); this.pending.set(offerId, { created: Date.now() }); tracker.send(this.#base({ numwant: 3, offers: [{ offer_id: offerId, offer }] })); } catch (error) { this.emit('error', error); } })); this.#prune(); }
  #base(extra) { return { action: 'announce', info_hash: this.infoHash, peer_id: this.peerId, uploaded: 0, downloaded: 0, left: 0, ...extra }; }
  async #message(tracker, message) { if (message['failure reason']) return this.emit('error', new Error(`Tracker rejected announce: ${message['failure reason']}`)); if (message.answer && message.offer_id && this.pending.has(message.offer_id)) { this.pending.delete(message.offer_id); return this.answerHandler(message.peer_id, message.answer, message.offer_id); } for (const item of message.offers ?? []) { if (!item?.offer || !item.offer_id || !message.peer_id || message.peer_id === this.peerId) continue; try { const answer = await this.answerFactory(message.peer_id, item.offer); tracker.send(this.#base({ to_peer_id: message.peer_id, offer_id: item.offer_id, answer })); } catch (error) { this.emit('error', error); } } }
  #prune() { const oldest = Date.now() - 60_000; for (const [id, item] of this.pending) if (item.created < oldest) this.pending.delete(id); }
}
