import { Emitter } from '../utils/events.js';
import { randomId } from '../utils/ids.js';
import { decodeChunk, encodeChunk } from '../utils/protocol.js';
export class TransferManager extends Emitter {
  constructor({ chunkSize = 16 * 1024, maxFileSize = 1024 * 1024 * 1024, maxIncomingTransfers = 4 } = {}) { super(); this.chunkSize = chunkSize; this.maxFileSize = maxFileSize; this.maxIncomingTransfers = maxIncomingTransfers; this.incoming = new Map(); this.outgoing = new Map(); }
  async send(peer, file) { if (!(file instanceof Blob)) throw new TypeError('file must be a Blob or File'); if (file.size > this.maxFileSize) throw new RangeError('File exceeds maxFileSize'); const id = randomId(); const totalChunks = Math.ceil(file.size / this.chunkSize); const state = { id, peer, file, name: file.name ?? 'file', type: file.type || 'application/octet-stream', size: file.size, totalChunks, transferred: 0, cancelled: false }; this.outgoing.set(id, state); await peer.send(JSON.stringify({ type: 'file-start', id, name: state.name, mime: state.type, size: state.size, totalChunks, chunkSize: this.chunkSize })); this.emit('file-start', peer, snapshot(state)); try { const digest = await hashBlob(file); for (let index = 0; index < totalChunks; index++) { if (state.cancelled) throw cancelled(); const bytes = await file.slice(index * this.chunkSize, Math.min(file.size, (index + 1) * this.chunkSize)).arrayBuffer(); await peer.send(encodeChunk(id, index, bytes)); state.transferred += bytes.byteLength; this.emit('file-progress', peer, snapshot(state)); } await peer.send(JSON.stringify({ type: 'file-end', id, sha256: digest })); this.emit('file-complete', peer, snapshot(state)); return snapshot(state); } catch (error) { if (!state.cancelled) this.emit('file-error', peer, snapshot(state), error); throw error; } finally { this.outgoing.delete(id); } }
  cancel(id) { const state = this.outgoing.get(id) ?? this.incoming.get(id); if (!state) return false; state.cancelled = true; state.peer.send(JSON.stringify({ type: 'file-cancel', id })).catch(() => {}); this.emit('file-cancel', state.peer, snapshot(state)); return true; }
  async receive(peer, data) { if (typeof data === 'string') return this.#control(peer, data); if (data instanceof Blob) data = await data.arrayBuffer(); if (data instanceof ArrayBuffer) { const chunk = decodeChunk(data); if (chunk) return this.#chunk(peer, chunk); } return false; }
  #control(peer, raw) { let message; try { message = JSON.parse(raw); } catch { return false; } if (!message?.type?.startsWith('file-')) return false; if (message.type === 'file-start') { if (!validStart(message, this.maxFileSize) || this.incoming.size >= this.maxIncomingTransfers) return false; const state = { ...message, peer, type: message.mime, transferred: 0, chunks: new Array(message.totalChunks), cancelled: false }; this.incoming.set(message.id, state); this.emit('file-start', peer, snapshot(state)); return true; } const state = this.incoming.get(message.id); if (!state) return false; if (message.type === 'file-cancel') { state.cancelled = true; this.incoming.delete(message.id); this.emit('file-cancel', peer, snapshot(state)); return true; } if (message.type === 'file-end') return this.#complete(state, message.sha256); return false; }
  #chunk(peer, { id, index, bytes }) { const state = this.incoming.get(id); if (!state || state.peer !== peer || state.cancelled || !Number.isInteger(index) || index < 0 || index >= state.totalChunks || state.chunks[index]) return false; const expected = index === state.totalChunks - 1 ? state.size - index * state.chunkSize : state.chunkSize; if (bytes.byteLength > state.chunkSize || bytes.byteLength !== expected) { this.incoming.delete(id); this.emit('file-error', peer, snapshot(state), new Error('Invalid file chunk size')); return false; } state.chunks[index] = bytes; state.transferred += bytes.byteLength; this.emit('file-progress', peer, snapshot(state)); return true; }
  async #complete(state, expectedHash) { if (state.cancelled || state.chunks.some((chunk) => !chunk)) return this.#error(state, new Error('File ended before all chunks arrived')); const file = new File(state.chunks, state.name, { type: state.type }); const actualHash = await hashBlob(file); if (!expectedHash || actualHash !== expectedHash) return this.#error(state, new Error('File integrity check failed')); this.incoming.delete(state.id); this.emit('file-complete', state.peer, { ...snapshot(state), file, sha256: actualHash }); }
  #error(state, error) { this.incoming.delete(state.id); this.emit('file-error', state.peer, snapshot(state), error); }
}
function validStart(m, max) { return typeof m.id === 'string' && typeof m.name === 'string' && Number.isSafeInteger(m.size) && m.size >= 0 && m.size <= max && Number.isSafeInteger(m.totalChunks) && m.totalChunks >= 0 && Number.isSafeInteger(m.chunkSize) && m.chunkSize > 0 && m.chunkSize <= 64 * 1024 && m.totalChunks === Math.ceil(m.size / m.chunkSize); }
function snapshot(state) { return { id: state.id, name: state.name, size: state.size, type: state.type, transferred: state.transferred, progress: state.size ? state.transferred / state.size : 1, totalChunks: state.totalChunks }; }
function cancelled() { const error = new Error('Transfer cancelled'); error.name = 'AbortError'; return error; }
async function hashBlob(blob) { const data = await blob.arrayBuffer(); const hash = new Uint8Array(await crypto.subtle.digest('SHA-256', data)); return [...hash].map((byte) => byte.toString(16).padStart(2, '0')).join(''); }
